artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/gagan3012/online-shoppers-intention-/master/online_shoppers_intention.csv
  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data

data_validation_config:
  clean_data_dir: clean_data
  serialized_objects_dir: serialized_objects
  data_csv_file: online_shoppers_intention.csv

data_transformation_config:
  transformed_data_dir: transformed_data

# model_trainer_config:
#   trained_model_dir: trained_model
#   trained_model_name: model.pkl